name: volume-sdf
radius: ${model.radius}
feature_dim: 13
grad_type: analytic
finite_difference_eps: progressive
isosurface:
  method: mc
  resolution: 512
  chunk: 2097152
  threshold: 0.
xyz_encoding_config:
  otype: ProgressiveBandHashGrid
  n_levels: 16
  n_features_per_level: 2
  log2_hashmap_size: 19
  base_resolution: 16
  per_level_scale: 1.447269237440378
    # per_level_scale: 1.5
  interpolation: Linear
  include_xyz: true
  # start from start_step and start_level, increase feature level by 1 very update_steps steps
  start_level: 4
  update_steps: 125
  start_step: 500
mlp_network_config:
  otype: VanillaMLP
  output_activation: none
  n_neurons: 64
  n_hidden_layers: 1
  sphere_init: true
  sphere_init_radius: 0.5
  weight_norm: true
